
export const GET_BUSINESS_START = 'GET_BUSINESS_START';
export const GET_BUSINESS_SUCCESS = 'GET_BUSINESS_SUCCESS';
export const GET_BUSINESS_FAIL = 'GET_BUSINESS_FAIL';
export const GET_BUSINESS_REFRESH = 'GET_BUSINESS_REFRESH';


export const GET_DRIVERS_LOCATION_START = 'GET_DRIVERS_LOCATION_START';
export const GET_DRIVERS_LOCATION_SUCCESS = 'GET_DRIVERS_LOCATION_SUCCESS';
export const GET_DRIVERS_LOCATION_FAIL = 'GET_DRIVERS_LOCATION_FAIL';
